/**
 * power_bi_modelo
 * Modelo de Conector Power BI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InlineResponse200Value (
  /* id */
  id: Option[String] = None,
  /* isReadOnly */
  isReadOnly: Option[Boolean] = None,
  /* isOnDedicatedCapacity */
  isOnDedicatedCapacity: Option[Boolean] = None,
  /* name */
  name: Option[String] = None,
  /* dataflowStorageId */
  dataflowStorageId: Option[String] = None
) extends ApiModel


